apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
        - name: book-app
          image: hashinig/book-app:latest  
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-pass
            - name: MONGO_HOST
              value: mongo-svc
---
apiVersion: v1
kind: Service
metadata:
  name: book-app-svc
spec:
  type: NodePort
  selector:
    app: book-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32001  
